server:
  port: 8090



spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include:
          - beans
          - health
          - metrics
          - env